version: '3.4'

services:

  sql-server-db:
    container_name: SQL_Server
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlvol2:/var/opt/mssql
    ports:
      - "1404:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"

  schoolpostponementapi:
    image: ${DOCKER_REGISTRY-}schoolpostponementapi
    build:
      context: .
      dockerfile: SchoolPostponementAPI/Dockerfile

  travelapprovalapi:
    image: ${DOCKER_REGISTRY-}travelapprovalapi
    build:
      context: .
      dockerfile: TravelApprovalAPI/Dockerfile

  cashallowanceapi:
    image: ${DOCKER_REGISTRY-}cashallowanceapi
    build:
      context: .
      dockerfile: CashAllowanceAPI/Dockerfile

  cashallowanclessthan42:
    image: ${DOCKER_REGISTRY-}cashallowanclessthan42
    build:
      context: .
      dockerfile: CashAllowancLessThan42/Dockerfile

volumes:
  sqlvol2:



