version: '3.4'

services:

  sql-server-db:
    container_name: SQL_Server2
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlvol2:/var/opt/mssql
    ports:
      - "1404:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"

  consul:
    image: consul:latest
    container_name: consul_server2
    network_mode: bridge
    ports:
      - "8501:8500"
      -  "8601:8600/udp"
    command:  consul agent -dev -server -ui -node=server-1 -bootstrap-expect=1 -client="0.0.0.0"

  schoolpostponementapi:
    image: ${DOCKER_REGISTRY-}schoolpostponementapi
    build:
      context: .
      dockerfile: SchoolPostponementAPI/Dockerfile
    ports:
      - "41025:80"
      - "40025:443"

  travelapprovalapi:
    image: ${DOCKER_REGISTRY-}travelapprovalapi
    build:
      context: .
      dockerfile: TravelApprovalAPI/Dockerfile
    ports:
      - "51000:80"
      - "50000:443"

  cashallowanceapi:
    image: ${DOCKER_REGISTRY-}cashallowanceapi
    build:
      context: .
      dockerfile: CashAllowanceAPI/Dockerfile
    ports:
      - "51001:80"
      - "50001:443"

  cashallowanclessthan42:
    image: ${DOCKER_REGISTRY-}cashallowanclessthan42
    build:
      context: .
      dockerfile: CashAllowancLessThan42/Dockerfile
    ports:
      - "51002:80"
      - "50002:443"

  alonepostponement:
    image: ${DOCKER_REGISTRY-}alonepostponement
    build:
      context: .
      dockerfile: AlonePostponement/Dockerfile
    ports:
      - "41029:80"
      - "40029:443"

  brotherinservicepostponementapi:
    image: ${DOCKER_REGISTRY-}brotherinservicepostponementapi
    build:
      context: .
      dockerfile: BrotherInServicePostponementAPI/Dockerfile
    ports:
      - "41030:80"
      - "40030:443"

volumes:
  sqlvol2: